### PR TITLE
Implement optional fuzzy search

### PR DESCRIPTION
**Pull request by trading-peter**
Using the super fast fuzzysearch module and a new option we can now perform a fuzzy search for emojis. This is espicaly usefull if one don't know the english spelling of some keywords that well.

### CODE REVIEW

**Comment by watilde** [comment]
Wooo this feature looks nice! Could you take a look at the error on travis CI?
https://travis-ci.org/watilde/emoji-cli/builds/163655669

It would be great if you could fix it 😺

**Comment by trading-peter** [comment]
Should be all good now. Missed a space...

**Comment by watilde** [comment]
A w e s o m e !

I will add a test case for the fuzzy search later(maybe this weekend), or you could add it if you have an interest in it 😼

**Comment by trading-peter** [comment]
I added some tests. While writing them I realized that fuzzy search didn't search in the emoji name, only the keywords. I fixed that too.

**Comment by watilde** [comment]
Great!! That's the benefit of the test we can receive. Let me merge this and ship it immediately :satisfied:

Thanks for putting this together and following up hardly

**Comment by watilde** [comment]
This is shipped as v0.3.0 🎉 
- Git tag: https://github.com/watilde/emoji-cli/releases/tag/v0.3.0
- Contributors: https://github.com/watilde/emoji-cli/blob/master/package.json#L23
- Change log: https://github.com/watilde/emoji-cli/blob/master/CHANGELOG.md#v030---2016-09-30

**Pull request merged**
